algo = input('Digite algo para saber suas propiedades:')
print('o que você digitou possui as seguintes caracteristicas')
print(type(algo))
print(f'{algo} é isidentifier?',algo.isidentifier())
print(f'{algo} é alnum?',algo.isalnum())
print(f'{algo} é alpha?',algo.isalpha())
print(f'{algo} é ascii?',algo.isascii())
print(f'{algo} é digit?',algo.isdigit())
print(f'{algo} é decimal?',algo.isdecimal())
print(f'{algo} é lower?',algo.islower())
print(f'{algo} é numeric?',algo.isnumeric())
print(f'{algo} é printable',algo.isprintable())
print(f'{algo} é space?',algo.isspace())
print(f'{algo} é title?',algo.istitle())
print(f'{algo} é upper?',algo.isupper())