numero = int(input('Digite o um numero para descobrir suas tabuada do 0 ao 9'))
print(f'A tabudada de {numero} é a seguintes mutiplicações')
print(f'{numero} * 0 é {numero*0}')
print(f'{numero} * 1 é {numero*1}')
print(f'{numero} * 2 é {numero*2}')
print(f'{numero} * 3 é {numero*3}')
print(f'{numero} * 4 é {numero*4}')
print(f'{numero} * 5 é {numero*5}')
print(f'{numero} * 6 é {numero*6}')
print(f'{numero} * 7 é {numero*7}')
print(f'{numero} * 8 é {numero*8}')
print(f'{numero} * 9 é {numero*9}')
print(f'{numero} * 10 é {numero*10}')